# Generated by Django 4.0 on 2022-10-30 19:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=1024)),
                ('pin', models.CharField(max_length=16)),
                ('unique_value', models.UUIDField(default=uuid.UUID('1534d1a4-3599-4d7a-b12e-14acd39b2497'))),
            ],
        ),
    ]
